### ISSUE TITLE
 iOS: Printing library does not print anything but (a4 portrait) mode on iOS, and if you try to print anything else like [a4 landscape, a5 portrait, a5 landscape] it will layout it on (a4 portrait) which will print in a wrong way

### ISSUE THREAD

**Issue by xSuperMu** [DavBfr/dart_pdf#510]
I have this code on an otherwise empty project:

I'm using iPad(5th generation) iOS(13.7)

dependencies:
  printing: ^3.7.2

```dart
// ignore_for_file: public_member_api_docs

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

void main() => runApp(const MyApp('Printing Demo'));

class MyApp extends StatelessWidget {
  const MyApp(this.title);

  final String title;

  final largeText =
      """Contrary to popular belief, Lorem Ipsum is not simply random text.
   It has roots in a piece of classical Latin literature from 45 BC, 
   making it over 2000 years old. Richard McClintock, 
   a Latin professor at Hampden-Sydney College in Virginia, 
   looked up one of the more obscure Latin words, consectetur, 
   from a Lorem Ipsum passage, and going through the cites of the word in classical literature,
    discovered the undoubtable source. 
    Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of 
    "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
     written in 45 BC. This book is a treatise on the theory of ethics, 
     very popular during the Renaissance. The first line of Lorem Ipsum, 
     "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for 
    those interested. Sections 1.10.32 and 1.10.33 from 
    "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original 
    form, accompanied by English versions from the 1914 translation by H. Rackham.""";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text(title)),
        body: PdfPreview(
          build: (format) => _generatePdf(format, largeText),
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4.landscape,
        build: (context) {
          return pw.Center(
            child: pw.Text(title),
          );
        },
      ),
    );

    return pdf.save();
  }
}

```
**The issue with (pageFormat: PdfPageFormat.a4.landscape)**

The PdfPreview layouts the view correctly (a4 landscape), like this:

![1](https://user-images.githubusercontent.com/17935590/103416466-9bba0c80-4b8f-11eb-9f1f-02a69b7ea554.png)

But, When i try to print, this happens:
It displays an (a4 portrait) view, instead of (a4 landscape) view.

![2](https://user-images.githubusercontent.com/17935590/103416470-9eb4fd00-4b8f-11eb-9ed0-f6ec24a741ed.png)

**The issue with (pageFormat: PdfPageFormat.a5.portrait)**
The PdfPreview layouts the view correctly (a5 portrait), like this:
![3](https://user-images.githubusercontent.com/17935590/103416758-b0e36b00-4b90-11eb-933e-8c3f9563895e.png)

But, When i try to print, this happens:
It displays an (a4 portrait) view, instead of (a5 portrait) view.

![4](https://user-images.githubusercontent.com/17935590/103416765-b50f8880-4b90-11eb-9b4e-eb3924aeb3d0.png)

**The issue with (pageFormat: PdfPageFormat.a5.landscape)**
The PdfPreview layouts the view correctly (a5 landscape), like this:
![5](https://user-images.githubusercontent.com/17935590/103420611-d9736100-4ba0-11eb-93e5-aa2332dd906c.png)

But, When i try to print, this happens:
It displays an (a4 portrait) view, instead of (a5 landscape) view.
![6](https://user-images.githubusercontent.com/17935590/103420612-dc6e5180-4ba0-11eb-83b4-1bdcebf4d32d.png)

## Logs

Flutter doctor output: 

```
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.25.0-4.0.pre at /Users/muhammadelsayed/Documents/PRO/flutter
    • Framework revision a7f5fd5360 (4 weeks ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/muhammadelsayed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.4
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPad (5th generation) (mobile) • 9930B1AA-426E-4769-8B7C-182FD210CF45 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7
      (simulator)

• No issues found!

```

**Comment by DavBfr** [comment]
You cannot force a page format when printing: The final format depends on what the user has in his printer and the type of printer he uses.
You have to use the format passed as an argument to the callback.

**Comment by xSuperMu** [comment]
it prints what I need correctly.
but the users of my app reported that the view on the screen was not as expected.
like the screenshots above.

Would you please tell me how to use the format passed with this example

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    onLayout: (PdfPageFormat format)
    async => pdfData
);

```

**Comment by xSuperMu** [comment]
> You cannot force a page format when printing: The final format depends on what the user has in his printer and the type of printer he uses.
> You have to use the format passed as an argument to the callback.

it prints what I need correctly.
but the users of my app reported that the view on the screen was not as expected.
like the screenshots above. (in the print dialog)

Would you please tell me how to use the format passed with this example

I want to layout the preview in the print dialog as (a5 landscape)
the pdfLink contains an (a5 landscape) pdf file

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    onLayout: (PdfPageFormat format)
    async => pdfData
);

```

**Comment by DavBfr** [comment]
Not possible in this case, iOS tries to accommodate and squeeze the PDF file into the actual page.

**Comment by xSuperMu** [comment]
> Not possible in this case, iOS tries to accommodate and squeeze the PDF file into the actual page.

let me explain what I need in a direct example

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    onLayout: (PdfPageFormat format)
    async => pdfData
);

```

The above code do the following .. 
as I said the pdfLink contains an (a5 landscape) pdf file

![Screen Shot 2020-12-31 at 8 38 19 PM](https://user-images.githubusercontent.com/17935590/103422070-43433900-4ba8-11eb-8ae1-75d1a70e776e.png)


when I copy the link of the pdf and paste it into safari and try to print it

This happens (which is the expected behavior that I mean)

![Simulator Screen Shot - iPad (5th generation) - 2020-12-31 at 20 38 47](https://user-images.githubusercontent.com/17935590/103422074-46d6c000-4ba8-11eb-8082-8dfa002ebe17.png)

**Comment by DavBfr** [comment]
I guess you'll have to find a way to pass the correct orientation to the print API here:
https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/PrintJob.swift#L64

as explained in this documentation: https://developer.apple.com/library/archive/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/Printing/Printing.html#//apple_ref/doc/uid/TP40010156-CH12-SW17

**Comment by xSuperMu** [comment]
> I guess you'll have to find a way to pass the correct orientation to the print API here:
> https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/PrintJob.swift#L64
> 
> as explained in this documentation: https://developer.apple.com/library/archive/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/Printing/Printing.html#//apple_ref/doc/uid/TP40010156-CH12-SW17

This is too complex for me as a beginner to flutter!

I thought the the Print library will take care of this complexity.

Is there any other way to tackle this issue?

**Comment by DavBfr** [comment]
I can add a parameter to set the default orientation: portrait or landscape. I can't detect it from the pdf file, as the pages are independent and can be one way or another. But it's easy to get the first-page size and decide on your side.

I'll need a few [Coffees](https://www.buymeacoffee.com/JORBmbw9h) to do that, as it has to be implemented on iOS, Android, macOS, and Windows!

**Comment by xSuperMu** [comment]
> Not possible in this case, iOS tries to accommodate and squeeze the PDF file into the actual page.

let me explain what I need in a direct example

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    onLayout: (PdfPageFormat format)
    async => pdfData
);

```

The above code does the following .. 
as I said, the pdfLink contains an (a5 landscape) pdf file

![6](https://user-images.githubusercontent.com/17935590/103423651-74c00280-4bb0-11eb-9aae-ca06ad50ef31.png)

when I copy the link of the pdf and paste it into safari and try to print it

**This happens (which is the expected behavior that I mean)**

![5](https://user-images.githubusercontent.com/17935590/103423647-7093e500-4bb0-11eb-8e83-39651973c194.png)


Can you help me to do as in the above screenshot?

**Comment by xSuperMu** [comment]
> I can add a parameter to set the default orientation: portrait or landscape. I can't detect it from the pdf file, as the pages are independent and can be one way or another. But it's easy to get the first-page size and decide on your side.
> 
> I'll need a few [Coffees](https://www.buymeacoffee.com/JORBmbw9h) to do that, as it has to be implemented on iOS, Android, macOS, and Windows!

How much does a coffee costs? if that what would make you fix this issue.

**Comment by DavBfr** [comment]
Yes, that's possible.

**Comment by xSuperMu** [comment]
> Yes, that's possible.
> 
> on Android: https://stackoverflow.com/questions/40042771/how-to-change-the-default-portrait-orientation-to-landscape-in-android-print-f

Thank you so much. That's really helpful.
But, what about iOS? That's the problem I'm facing with Print library right now!

Would you please help me for this issue?

**Comment by DavBfr** [comment]
Yes, it's possible with iOS too.

**Comment by xSuperMu** [comment]
> Yes, it's possible with iOS too.

Actually I've tried myself to print (a5 landscape) (or anything else rather than a4 portrait) but the printed paper was layout in a wrong way, it was printed as if it was printed as (a4 portrait). just like what appears in the preview layout (the print dialog that appears before clicking print), **The original issue, which is  exactly what I asked for help for it**.

What I mean is this: 
**The Printing library does not print anything but (a4 portrait) mode on iOS, and if you try to print anything else like 
[a4 landscape, a5 portrait, a5 landscape] it will layout it on (a4 portrait) which will print in a wrong way**

Till this moment, the issue is not fixed for iOS!

So, can you please help us fixing this issue? Showing us something like a (documentation example) of how to make the library to print what is supposed to be printed as configured?

Can you please improve the library by making an attribute to accept the orientation (portrait - landscape) and size (a4 - a5)?

**Comment by DavBfr** [comment]
@xSuperMu I said it's possible to fix, it's just not my priority now.

**Comment by DavBfr** [comment]
Fixed in printing version 4.0.0
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by xSuperMu** [comment]
> Fixed in printing version 4.0.0
> Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

Thank you for your efforts. I do really appreciate that. and of course I'll will not hesitate.

But,


Usinge Print: ^4.0.0

I've tried this code to test (a5 portrait), knowing that pdfLink have (a5 landscape pdf):

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    format: PdfPageFormat.a5,
    onLayout: (PdfPageFormat format)
    async => pdfData
);
```

**And this was the result: (Still behave in a wrong & unexpected way)**

![Simulator Screen Shot - iPad mini (5th generation) - 2021-01-07 at 16 45 31](https://user-images.githubusercontent.com/17935590/103906568-c7e20a00-5108-11eb-97da-66fa29920845.png)



Then, I've tried this code to test (a5 landscape):

```dart

http.Response resp = await http.get(pdfLink);
var pdfData =resp.bodyBytes;

await Printing.layoutPdf(
    format: PdfPageFormat.a5.landscape,
    onLayout: (PdfPageFormat format)
    async => pdfData
);
```
**And this was the result: **

![Simulator Screen Shot - iPad mini (5th generation) - 2021-01-07 at 16 54 36](https://user-images.githubusercontent.com/17935590/103906925-3e7f0780-5109-11eb-9418-0397864459b8.png)


The issue is still the same!
**Progress have been made in the library, but it still behave in a wrong way as you've seen the screenshots above.**

What do you think?

**Comment by DavBfr** [comment]
If your printer has a4 sheets, it will never correctly print an a5 pdf. You just need to use the right paper on your printer.

**Comment by xSuperMu** [comment]
My printers has a5 sheets only, because that what I only need. and I print on (a5 landscape).

I just test the library on different paper sheets to make a point and to define where the problem is!

And, unfortunately, the issue is still active!

**Comment by xSuperMu** [comment]
After a lot of testing, I figured out this:

When I choose  (a5 landscape), it layouts on (a4 landscape) (wrong behavior)
when I choose (a4 landscape), it layout on (a4 landscape) (as expected)

Which brings us to the issue:

**The Printing library does not print anything but (a4 portrait, a4 landscape) mode on iOS, and if you try to print 
(a5 portrait) it will layout it on (a4 portrait) which will print in a wrong way
( a5 landscape) it will layout it on (a4 landscape) which will print in a wrong way
**
