### ISSUE TITLE
TypeError: Cannot read property 'layout' of null at multi_page.MultiPage.new.generate at document$.Document.new.addPage

### ISSUE THREAD

**Issue by kostas95** [DavBfr/dart_pdf#584]
**Describe the bug**

I'm using ```pdf``` and ```printing``` for exporting widgets to pdf. My app was working fine all the time until today, when I tried to export a document and I got the following error.

``` 
TypeError: Cannot read property 'layout' of null
    at multi_page.MultiPage.new.generate (http://localhost:51446/packages/pdf/src/widgets/multi_page.dart.lib.js:456:26)
    at document$.Document.new.addPage (http://localhost:51446/packages/pdf/src/widgets/container.dart.lib.js:4744:12)
    at exportPdf (this is my function that exports the pdf)
    at http://localhost:51446/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:51446/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:51446/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:51446/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:51446/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:51446/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51446/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:51446/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:51446/dart_sdk.js:39182:13)
    at http://localhost:51446/dart_sdk.js:34689:9
```

My ```pubspec.yaml``` contains the following:

```printing: ^5.0.1```
```pdf: ^3.0.1```

**To Reproduce**

This is the part of my code, that the error occurs
```dart
pdf.addPage(
        pw.MultiPage(
            theme: pw.ThemeData.withFont(
              base: pw.Font.ttf(await rootBundle.load("assets/pdf-assets/fonts/open-sans/OpenSans-Regular.ttf")),
              bold: pw.Font.ttf(await rootBundle.load("assets/pdf-assets/fonts/open-sans/OpenSans-Bold.ttf")),
              italic: pw.Font.ttf(await rootBundle.load("assets/pdf-assets/fonts/open-sans/OpenSans-Italic.ttf")),
              icons: pw.Font.ttf(await rootBundle.load('assets/pdf-assets/material.ttf')),
            ),
            header: buildHeader,
            footer: buildFooter,
            maxPages: 1000,
            build: (pw.Context context) => <pw.Widget>[My widgets right here]
        )
    );
```

**Expected behavior**
Export the pdf without any error.

**Flutter Doctor**

```
[√] Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.19041.746], locale el-GR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

• No issues found!

```

**Desktop (please complete the following information):**
 - [√] iOS
 - [√] Android
 - [√] Browser
 - [√] Windows
 - [√] Linux

**Additional context**
Do I have to downgrade the package? Is the issue happening because of ```Flutter 2.0.0```? Or am I doing something wrong?

**Comment by DavBfr** [comment]
Is it fixed in printing-5.0.2?

**Comment by kostas95** [comment]
I changed in my ```pubspec.yaml``` file the ```printing``` package to ```^5.0.2``` and I ran ```pub get```, but the same error occurs.

**Comment by DavBfr** [comment]
I don't know what you're doing, I can't reproduce it.

**Comment by kostas95** [comment]
The export is working perfectly now, and I did not fix anything. I don't understand what happened, but we can close this issue
