### ISSUE TITLE
Loading NotoSans-Regular.ttf fails

### ISSUE THREAD

**Issue by zimmi** [DavBfr/dart_pdf#7]
Hi, I'm trying to generate a PDF inside a flutter app, using a custom TrueType font, NotoSans.

This fails with `NoSuchMethodError: The method 'replaceAll' was called on null.`, on line `baseFont = "/" + font.fontName.replaceAll(" ", "");`. The offending code is [here](https://github.com/DavBfr/dart_pdf/blob/master/pdf/lib/src/ttffont.dart#L34), it seems like `font.fontName` is null for this particular font, not sure if this is a problem with the font file or the parsing. Maybe it should deal with a missing name more gracefully?

To reproduce:
1. Download the font package: https://www.google.com/get/noto/#sans-lgc
1. Extract `NotoSans-Regular.ttf`
1. Try to create the font, like this:
```dart
var pdf = PDFDocument();
var page = PDFPage(pdf);
var bytes = await rootBundle.load('assets/NotoSans-Regular.ttf');
var font = PDFTTFFont(pdf, bytes);
```

Thanks for writing this library!

**Comment by DavBfr** [comment]
Fixed in pdf 1.0.6
Thanks

**Comment by zimmi** [comment]
That was quick, thanks!

**Comment by kiko555** [comment]
I try to import same font at pdf 1.3.7, but while return to printing got "prepare preview...." loading...

Printing.layoutPdf(onLayout: buildPdf4);

Future<List<int>> buildPdf4(PdfPageFormat format) async {
    final PdfDocument pdfNew = PdfDocument();

    var font = await rootBundle.load("fonts/NotoSerifTC-Black.otf");
    PdfTtfFont ttf = PdfTtfFont(pdfNew, font);

    final page = new PdfPage(pdfNew, pageFormat: PDFPageFormat.A4);
    final g = page.getGraphics();

    g.drawString(ttf, 20.0, "Dart is awesome", 50.0, 30.0);

    return pdfNew.save();
}

**Comment by DavBfr** [comment]
otf is not ttf. This library is compatible only with ttf fonts.

**Comment by kiko555** [comment]
thank DavBfr quick reply.
I try change the font to ttf one "OpenSans-Bold.ttf",
but the problem still appear.

**Comment by DavBfr** [comment]
What is the error?

**Comment by kiko555** [comment]
I change the font to ttf type.
Then return to printing,but the printing alway  show "prepare preview...." 
<img width="270" alt="2019-04-11 21 14 54" src="https://user-images.githubusercontent.com/1998482/55960387-40e7cf80-5c9f-11e9-8ecb-ba3b61c39010.png">

**Comment by kiko555** [comment]
the problem is my fault, I forgot add the ttf font to pubspec.yaml
thank DavBfr!!
![Screenshot_1555087074](https://user-images.githubusercontent.com/1998482/56052620-7e725880-5d84-11e9-876b-6a2c4defd95e.png)
